### PR TITLE
Add new GettingStarted notebook

### PR DESCRIPTION
**Pull request by Effieloveslife**

### CODE REVIEW

**Comment by mivade** [comment]
This is a great start. Do you want to add a section about power (it is currently blank) or should that go in another tutorial?

**Comment by Effieloveslife** [comment]
Thanks! 

CW has suggested adding a section about wavelet computation. If that fits better in another notebook, say an EEG analysis tutorial, I can remove that from this notebook.

I will finish the low-pass/high-pass/band-stop filtering part.

**Comment by mivade** [comment]
I think a separate notebook would be better for that.

**Comment by Effieloveslife** [comment]
Sounds good! I'll work on the filtering part.

**Comment by Effieloveslife** [comment]
I just committed some final edits after discussing with CW.

**Comment by mivade** [comment]
I suggest the following updates:

- Update this to use the current master branch
- Use Python 3 (this will require using `print` as a function everywhere)
- Remove the numbers in the section headers

**Comment by Effieloveslife** [comment]
The h5 loading error is now fixed and the tutorial notebook is verified with the current master branch ptsa_new.

**Comment by Effieloveslife** [comment]
Thank you for your help and guidance!

**Pull request merged**
