### PR TITLE
Improve HDF5 serialization

### PR DESCRIPTION
**Pull request by mivade**
- [x] Handle strings
- [x] Handle JSON-encodable types
- [x] Integrate with `TimeSeries.to_hdf`/`from_hdf`
- [x] Test we can still read the base64-saved files
- [x] Add less trivial test cases

### CODE REVIEW

**Comment by mivade** [comment]
How can you approve these changes when there are two unfilled check boxes?

**Comment by ctw** [comment]
Ooops

**Comment by mivade** [comment]
This doesn't quite work yet except in the trivial test cases. I'm not quite sure what the issue is yet.

**Comment by mivade** [comment]
Looks like the problem is that `xarray` likes to make every coordinate itself a `TimeSeries`...  Luckily I can work around this by using the `.data` attribute which gives just the underlying data.

Why are we using `xarray` again?

**Pull request merged**
